### PR TITLE
Assignment 02.Git.Local and 03.Git.Hosting

### PR DESCRIPTION
**Pull request by erikanuernberg**
Added commands and bash script

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
Please do not remove not your files, I see, README.md from my demo was deleted

**Comment by pluhin** [comment]
@erikanuernberg 
Any updates?

**Comment by erikanuernberg** [comment]
@pluhin Added deletet README.md.

**Comment by pluhin** [comment]
Please, check all my commits, for markdown and missing part of report

**Review by pluhin — APPROVED** [review]
Good, approved

**Pull request merged**
