### PR TITLE
Valeryi Charnyshou HW

### PR DESCRIPTION
**Pull request by valeryicharnyshou**
Hello!
Could you please check my homework!
Thanks a lot!

### CODE REVIEW

**Comment by pluhin** [comment]
Can, you do rebase, I've merged already few PRs, then I can marge your PR

**Comment by valeryicharnyshou** [comment]
I'm afraid i didn't understand... what branches should i rebase?

**Comment by valeryicharnyshou** [comment]
git rebase m-sa2-11-19
git push
Should I execute these commands locally?

**Comment by pluhin** [comment]
> git rebase m-sa2-11-19
> git push
> Should I execute these commands locally?

Rebase  with m-sa2-11-19 in my branch, as I have been showed on last webinar

**Comment by valeryicharnyshou** [comment]
Can you please check?

**Pull request merged**
