### PR TITLE
08.Docker.Compose

### PR DESCRIPTION
**Pull request by streamx1**
Please, tell me how delete useless commit? I commit and push only 2 files, but I see they`re too many.

### CODE REVIEW

**Comment by pluhin** [comment]
Please exclude folder venv from your commit, it is to heavy

**Comment by pluhin** [comment]
> Please, tell me how delete useless commit? I commit and push only 2 files, but I see they`re too many.

You can squash commits: https://www.educative.io/answers/how-to-squash-commits-in-git

**Comment by streamx1** [comment]
> You can squash commits: https://www.educative.io/answers/how-to-squash-commits-in-git

Screenshot_3

**Comment by pluhin** [comment]
> > You can squash commits: https://www.educative.io/answers/how-to-squash-commits-in-git
> 
> Screenshot_3

example for your repo:
```
(⎈|icinga2-k3s:default)➜  sa.it-academy.by git:(master) git checkout md-sa2-23-23
branch 'md-sa2-23-23' set up to track 'origin/md-sa2-23-23'.
Switched to a new branch 'md-sa2-23-23'
(⎈|icinga2-k3s:default)➜  sa.it-academy.by git:(md-sa2-23-23) git log --oneline
(⎈|icinga2-k3s:default)➜  sa.it-academy.by git:(md-sa2-23-23) git rebase -i HEAD~10
```

then add replace `pick` by `f` (fixup) in the beginning of lines with commits which you would like to squash(fixup - better, not need to correct commit message):

```
pick 204355e1 07.Docker
f c946aebf Add Dockerfile and build workflow
f 1dac935b Add Dockerfile and build workflow1
f 3a0de364 Add Dockerfile and build workflow 2
f 91fe6d8d Add Dockerfile and build workflow 3
f 5fb6bb6b Add Dockerfile and build workflow 4
f 66e3cac2 Add Dockerfile and build workflow 5
f fcf0d18a Add Dockerfile and build workflow 6
pick e34d15ee 08.Docker.Compose
f 01b96a7e Delete Pavel_Karabanovich/14.K8s.Jenkins directory
f 5facd9aa Delete Pavel_Karabanovich/10.K8s.Install directory
f baa57090 Delete Pavel_Karabanovich/15.K8s.ArgoCD directory
f fee9d2fe Delete Pavel_Karabanovich/08.Docker directory
pick e75949bc added HW 12.k8s.Data.Security
pick 1ccead19 06. Ansible Workshop
pick 8d5a70b4 12.K8s.Data.Security
pick b14eb76f Update README.md
pick 2981ff6a 13.Kubernetes.Helm HW
pick aa76673b Done. 13. Kubernetes. Helm
pick 5effee47 13.Kubernetes.Helm HW
pick 788ae5cc 13.Kubernetes.Helm HW fix
pick 9a00bf8e 09.Kubernetes
pick 06085055 Rewrite commit
pick b411ae43 Update README.md
pick 599e54ab 07.Docker
pick a3c78411 15.K8s.Argocd

# Rebase 403bae11..4dfd8c12 onto 403bae11 (26 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup [-C | -c] <commit> = like "squash" but keep only the previous
#                    commit's log message, unless -C is used, in which case
#                    keep only this commit's message; -c is same as -C but
#                    opens the editor
```

then you can see:
```
Successfully rebased and updated refs/heads/md-sa2-23-23.
(⎈|icinga2-k3s:default)➜  sa.it-academy.by git:(md-sa2-23-23) git log --oneline
```

finally, you can force push your new history to remote:

```
(⎈|icinga2-k3s:default)➜  sa.it-academy.by git:(md-sa2-23-23) git push origin -f  
```

**Comment by streamx1** [comment]
Done.
Screenshot_4
Screenshot_5

**Comment by pluhin** [comment]
You have too many commits still in your PR

**Comment by pluhin** [comment]
Looks like your rebase was wrong, I see to many changes not in your folder
Please revert rebase, or reset to normal commit, please do not forget save your folder/latest tasks outside repo folder, then, after reset you can back them and make commit

**Comment by streamx1** [comment]
I did it before you told me squash commits. Now I commited again. Please check it. Thank you!

**Comment by pluhin** [comment]
Still to many commits, and changes not in your folders
image

**Comment by streamx1** [comment]
> Still too many commits, and changes not in your folders !

I understand it. But I don`t understand what did wrong compared to previous homeworks, why pushed in first time all my workshops and webinars although I commited only 2 files with my homeworks 08.Docker.Compouse.

I did this commands again:

Screenshot_6
Screenshot_7

**Comment by pluhin** [comment]
> > Still too many commits, and changes not in your folders !
> 
> I understand it. But I don`t understand what did wrong compared to previous homeworks, why pushed in first time all my workshops and webinars although I commited only 2 files with my homeworks 08.Docker.Compouse.
> 
> I did this commands again:
> 
> Screenshot_6 Screenshot_7

You should keep et least one commit during fixup or squashing

You cannot recover this by doing squash/fixup again and again, you need to revert all commits till normal one
please save you folder before outside your repo

**Comment by pluhin** [comment]
```
 4956  git clone git@github.com:streamx1/sa.it-academy.by.git
 4957  cd sa.it-academy.by
 4958  git checkout md-sa2-23-23
 4959  git pull
 4960  git log --oneline
 4961  vim .git/config
 4962  git rebase -i HEAD~10
 4963  git log --oneline
 4964  git reset --hard HEAD~2
 4965  ls -l Pavel_Karabanovich
 4966  ls -l Pavel_Karabanovich/08.Docker.Compose/
 4967  git log --oneline
 4968  git log 4e61fab1
 4969  git log --oneline
 4970  git reset --hard HEAD~12
 4971  git log --oneline
 4972  ls -l Pavel_Karabanovich/08.Docker.Compose
```

**Pull request closed without merging**
