### PR TITLE
Md sa2 27 24

### PR DESCRIPTION
**Pull request by YauheniKastsevich**
please, squash all my commits

### CODE REVIEW

**Comment by pluhin** [comment]
> please, squash all my commits

I cannot squash your commits, they are inside your repository, you should squash commit, not me

**Comment by YauheniKastsevich** [comment]
i squash my commits

**Comment by YauheniKastsevich** [comment]
i fix git ignore

**Review by pluhin — CHANGES_REQUESTED** [review]
I see still changes, please check maybe you added empty line

**Comment by YauheniKastsevich** [comment]
fix gitignore again

**Review by pluhin — APPROVED** [review]

**Pull request merged**
