### PR TITLE
Eduard Linkevich, Home task: 02.Git.Local

### PR DESCRIPTION
**Pull request by EduardLinkevich**

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
Missing report part for list of commits in each branch

**Comment by EduardLinkevich** [comment]
> Missing report part for list of commits in each branch

**Comment by EduardLinkevich** [comment]
I often executed "history".
-"... sql файлу который там, возможно он содержит конфликтную секцию"
yes, I did this specially, that git offer correction options

**Comment by EduardLinkevich** [comment]
Create slack/email integration push/commit events
Screenshot_1

what should I do?

**Comment by pluhin** [comment]
> Create slack/email integration push/commit events
> Screenshot_1
> 
> what should I do?

There are few steps description below in dockumentation

**Comment by EduardLinkevich** [comment]
I added screenshots of the slack and email notifications.

**Review by pluhin — APPROVED** [review]
Good, approved

**Pull request merged**
