### PR TITLE
10. Kubernetes installation

### PR DESCRIPTION
**Pull request by NataliaBelogolovaya**

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
Please remove k8s config from PR

**Comment by NataliaBelogolovaya** [comment]
add changes in 10. Kubernetes installation (WS)
add 11. Kubernetes. Basic objects

**Review by pluhin — CHANGES_REQUESTED** [review]
Secrets are still there, in your history
please remove
as one solution, you can use: https://github.com/pluhin/sa.it-academy.by/wiki/00.-To-read#how-to-revert-commit-with-secret-example

**Comment by NataliaBelogolovaya** [comment]
I deleted the extra commit with config in history, please, check it again

**Review by pluhin — APPROVED** [review]

**Pull request merged**
