### PR TITLE
08.Ansible.WS added

### PR DESCRIPTION
**Pull request by usertiger**

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
Missing ansible code, I see only run commands here

Please add ansible

**Comment by usertiger** [comment]
anisble code added, k9s added

**Review by pluhin — APPROVED** [review]
Good, approved

**Comment by usertiger** [comment]
Is it mean that 13.K8S approved too? Because I couldn't saw a green point on google sheets. Thanks.

**Pull request merged**
