### PR TITLE
Kazimirov 15. Kubernetes CI CD and 16. Technical and service monitoring

### PR DESCRIPTION
**Pull request by Kirilllka1993**

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
Please remove secrete (slack webhook) from PR
solution: https://github.com/pluhin/sa.it-academy.by/wiki/00.-To-read#how-to-revert-commit-with-secret-example

**Comment by Kirilllka1993** [comment]
Вроде убрал

**Comment by pluhin** [comment]
> Вроде убрал

nope, it is visible in the history, need to revert all commits include commit(s) with secrets, please save all new files before in separate folder, clean them and make new clear commit, please check more details in manual in my message

**Comment by Kirilllka1993** [comment]
Ну сейчас в истории коммитов не фигурирует этот урл. Вроде всё)

**Review by pluhin — APPROVED** [review]
good, approved

**Pull request merged**
